# Introduction to SASS {#beautify-sass}
One of the main problem with CSS is to handle the growing number of files and the code repetition. Nowadays, web developers mainly use [SASS](https://sass-lang.com/guide), which provides access to variables,  mathematical operators, nesting, thereby reducing the code complexity and extending the possibilities. [Rstudio](https://rstudio.com) developed the [{sass}](https://rstudio.github.io/sass/articles/sass.html) package, which makes it possible to use in Shiny apps or Rmarkdown documents. 

## Example
Below is an example of badly managed CSS code. Both `.class-1` and `.class-2` have the same color and border radius. Only the padding and font size change. This type of code increases the risk of
having contradictory CSS rules.

```css
.class-1{
  color: #33BEFF;
  padding: 10px 16px;
  font-size: 12px;
  border-radius: 3px;
}

.class-2{
  color: #33BEFF;
  padding: 5px 10px;
  font-size: 12px;
  border-radius: 3px;
}
```

We could gather all common properties in one generic class:

```css
.generic {
  color: #33BEFF;
  border-radius: 3px;
}

.specific-1 {
  padding: 10px 16px;
  font-size: 18px;
}

.specific2 {
  padding: 5px 10px;
  font-size: 12px;
}
```

On the HTML side, we add classes from the most generic to the most specific like:

```html
<div class="generic specific-1">My element</div>
<div class="generic specific-2">My element</div>
```

As an even more concrete example, take a look at the [bulma](https://bulma.io/documentation/elements/button/) button:

```html
<button class="button is-large is-fullwidth">Large</button>
```

Notice how easy it is to predict the style of the button. It will be large and take the maximum width. It is for sure more meaningful than `.class1`!