# Beautify with fresh {#beautify-with-fresh}
[{fresh}](https://github.com/dreamRs/fresh) is an R package developed by the dreamRs team, also authors of [shinyWidget](https://github.com/dreamRs/shinyWidgets) and [esquisse](https://github.com/dreamRs/esquisse). All dreamRs projects are clearly a great source of inspiration to design oustansding Shiny apps, I recommend the reader to explore!

## {fresh}, the big picture
CSS is probably the poor sibling of this book, which is mainly focused on R and JavaScript interactions. Nevertheless, it remains important to develop consistant themes. One of the main problem with CSS is to handle the growing number of files and the code repetition. Nowadays, web developers mainly use [SASS](https://sass-lang.com/guide), which provides access to variables,  mathematical operators, nesting, thereby reducing the code complexicity and extending the possibilities. [Rstudio](https://rstudio.com) developed the [sass](https://rstudio.github.io/sass/articles/sass.html) package, which makes it possible to use in Shiny apps or Rmarkdown documents. 