# Introduction to CSS {#beautify-css}
The first CSS version was released in 1996, that is 5 years later than HTML. Before CSS appeared, developers styled their pages with specific tags like `font`, which eventually made the HTML code hard to maintain. The current version of CSS is 3. While nowadays all web browsers support CSS, this was not the case at the very beginning! 

## How to include CSS?

There are 3 ways to include CSS in a web page:

  - Point to an external file `<link rel="stylesheet" href="style.css"/>`
  - Insert the style in the `head`
  - Insert the style at the tag level, through the `style` attribute

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="style.css" />
        <title>CSS</title>
        <style type="text/css">
          p {
            color: red;  
          }
        </style>
    </head>

    <body>
        <p style="color: red">Hello World</p>
        <p>Some text</p>
        <div>Plop</div>
    </body>
</html>
```

I recommend to follow the first method as much as you can so that you modify the CSS in only one place!

At the end of the day, your CSS script will look like the below example:

```css
tag1 {
  property1: value1;
  property2: value2;
}

tag2 {
  property1: value1;
}
```

All of the above methods apply to shiny:

  - External CSS file `tags$link(rel = "stylesheet", type="text/css", href="www/style.css")`.
  - Internal CSS `tags$head(tags$style("p {color: red;}"))`.
  - Inline CSS `p(style = "color:red;", "Red text")`.

## Apply CSS

### Basics
To apply CSS, we select a the tag , choose the property we want to change and give it a value:

```css
tag {
  property: value;
}
```

For instance, to set the color blue to the `p` tag, we would do:

```css
p {
  color: red;  
}
```

Now, how would we apply the same property to multiple tags? We separate tags by a comma:

```css
p, div {
  color: red;  
}
```

### Select by class, id
The method shown above applies to all selected tags. This is not necessarily what we want as we probably would like to filter. We first add a `class` to the first `p` tag. Best practice is to give it a meaningful name. 

```html
<p class="first-p"></p>
```

On the CSS side, we prefix the class by a `.`, as shown below:

```css
.first-p {
  color: red;  
}
```

To style unique elements, we may use `id`:

```css
#element {
  color: red;
}
```

### Apply CSS to single elements
Let's consider the following example:

```html
<p>Hello World! What's up?</p>
```

How would you change the color of the `World` word? We could not select the whole `p` element.
There exist specific tags like `div` and `span` which you can apply. As stated in \@chapter(web-intro-html), `span` may be used inside containers to surround words:

```
<p>Hello <span class="custom">World</span>! What's up?</p>
```

```css
.custom {
  color: red;
}
```

### Advanced selectors
Until now, we' seen how to select an element by the tag name, a class and an id. Yet, this is not enough. How would you select the below tag?

```html
<a data-toggle="dropdown">Tag</a>
```

#### Select nested tags
We consider 2 HTML tags. We only want the first `a` element to have a red text. 
We can't select by class `.nav-link` as it would also style the second element!
```html
<li class="nav-item">
  <a class="nav-link" href="#">Link</a>
</li>

<a class="nav-link" href="#">Link</a>
```

The idea is to select the first tag, that is `li`, then select it's child `a`:

```css
li a {
  color: red;
}
```

#### More complex attributes
To select by attribute, we use `tag[attribute]`
```html
<a data-toggle="dropdown">Tag</a>
<a data-toggle="my dropdown">Tag</a>
<a data-toggle="whatever">Tag</a>
```

The below CSS code, will select all `a` tags:

```css
a[data-toggle] {
  color: red;
}
```

while the following code, will only select the first `a` tag:


```css
a[data-toggle="dropdown"] {
  color: red;
}
```

The reason is that we exactly match the `dropdown` value!

We could be less specific: 

```css
a[data-toggle*="dropdown"] {
  color: red;
}
```

`*` checks whether the word `dropdown` is there but not the position.


#### Other selectors
TO DO

## Exercises
TO DO