# Foreword {.unnumbered}

> By Kenton Russel aka \@timelyportfolio

Since the initial commit (https://github.com/rstudio/shiny/commit/e28b3da1badfecb34235e74a43aac4e8da1641bc) of Shiny in June 2012, the project has grown rapidly with users around the world across nearly every domain. Until 2021, strangely though, there was nearly zero comprehensive resources collecting the scattered wisdom and experience of thousands of Shiny users and developers into a single definitive resource. While, Hadley Wickham's *Mastering Shiny* book [@wickham2021mastering] focuses on providing a solid background about Shiny and the best practices, this book addresses a specific gap between the beginner and advanced level, which is how to deeply customize and enhance Shiny applications, to the point where it looks indistinguishable from a classic web application.  As I read through the early drafts, I kept saying to myself with a smile, "Yes, finally".  This book fills a void covering some topics for which an Internet search might yield no useful results.

Successful open source requires skillful developers, active engaged users, and helpful supporters.  In the R/Shiny community, David Granjon, PhD fulfills all three roles as a prolific R package creator, educated and thoughtful user with domain expertise, and educator (workshops, posts, and forum responses).  I cannot think of anyone more qualified to write a book on Shiny, and I am so happy that David has spent the time to generously share his wisdom and experience in this excellent resource.