# Introduction {#intro}

There are various Shiny focused resources introducing [basic](https://shiny.rstudio.com/tutorial/) as well as advanced topics such as [modules](https://shiny.rstudio.com/articles/#modules) and [Javascript/R](https://js4shiny.com) interactions, however, handling advanced user interfaces design was never an emphasis. Clients often desire custom templates, yet this generally exceeds core features of Shiny (not out of the box). 

Generally, R App developers lack a significant background in web development and often find this requirement overwhelming. It was this sentiment that motivated writing this book, namely to provide readers the necessary knowledge to extend Shiny's layout, input widgets and output elements. This project officially started at the end of 2018 but was stopped when Joe Cheng revealed the upcoming [Mastering Shiny Book](https://mastering-shiny.org). Fortunately, the later, does not cover the customization of Shiny user interfaces. Besides, this book may constitute a good complement to the work in progress [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org) by the ThinkR team, where the link between Shiny and CSS/JavaScript is covered. 

This book is organized into four parts. 

  - We first go through the basics of HTML, JavaScript and jQuery and finish with a chapter dedicated to the partially hidden features of Shiny, yet so fun 
  - In part 2, we dive into the `{htmltools}` package, providing functions to create and manipulate shiny tags as well as manage dependencies 
  - Part 3 focuses on the development of a new template for Shiny by demonstrating examples from the `{tablerDash}`, `{bs4Dash`} and `{shinyMobile}` packages. These, and more may be explored further as part of the RinteRface project.
  - Part 4 present some tools of the R community, like `{fresh}`, to beautify apps with only few lines of code
