# Shiny, HTML, CSS and JavaScript {#shiny-intro}
In the book prerequisites, to get the most out of this book, it was recommended that the reader should be quite familiar with Shiny. In the two previous chapters, we quickly introduced HTML and JavaScript. However, in this chapter, we are going to see what Shiny has under the hood.

Shiny allows the development of web applications with R in minutes. Let's face it: this is quite mind blowing! While this may not be a production ready app, it will still be a fully functional, working prototype. Believe me, doing a web application with pure HTML/CSS and JavaScript is more difficult, especially for someone with a non-web developer background. 

Is Shiny less customizable than a classic web app? Not at all! Indeed, Shiny has its own engine to build HTML tags, through R, meaning that all HTML elements are available. You may also include any custom [JavaScript](https://shiny.rstudio.com/articles/packaging-javascript.html) or [CSS](https://mastering-shiny.org/advanced-ui.html) code. 

Do you remember about the first exercise in Chapter \@ref(survival-kit-html)?

```{r, eval=FALSE}
library(shiny)
p("Hello World")
```

The `p` function generates HTML (see chapter \@ref(htmltools-overview)). The main difference between HTML tags and Shiny tags is the absence of closing tag for Shiny. For instance, in raw HTML, we expect `<p>` to be closed by `</p>`. In Shiny, we only call `p(...)`, where `...` may be attributes like class/id or children tags.

In this chapter, we will answer to the following questions:

- What web dependencies is Shiny based on?
- How is R/JavaScript communication achieved?
- How does Shiny deal with inputs? 


In Chapter \@ref(htmltools-dependencies) we will explore tools to manage HTML dependencies. In Chapter \@ref(insert-tabs), we will see a special case to insert dependencies during the app runtime. Finally, in the last part of this book, we will be designing custom inputs and knowing how to debug them is priceless.