
on:
  push:
    branches: [main, master, deploy**]
  repository_dispatch:
    types:
      - all
      - deploy

name: Deploy Apps

jobs:
  deploy:
    runs-on: ubuntu-20.04

    name: "unleash-shiny"

    env:
      R_KEEP_PKG_SOURCE: yes
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: "3.6"
          use-public-rspm: true

      # - uses: r-lib/actions/setup-renv@v1
      #   with:
      #     cache-version: 2
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 1
          extra-packages: |
            rsconnect
            rprojroot

      - name: Deploy
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: >
          Rscript 'scripts/deploy_on_ci.R'
